global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  webhook_configs:
  - url: 'https://hooks.slack.com/services/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'
    send_resolved: true
