apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      team: metrics
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-example
      port: 9093
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: prometheus
