apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: metrics
  name: prometheus-operator
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app: l7mp-prometheus
